// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Box: typeof import('./src/components/Box.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Generator: typeof import('./src/components/Generator.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    ScrollingPhrase: typeof import('./src/components/ScrollingPhrase.vue')['default']
  }
}
